title: AwesomeJT
logo: /assets/images/logo.avif
baseurl: /awesome-jekyll-theme

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration. Uncomment a channel to enable. Add new channels as needed.
# Channels will be displayed in the order listed.
# Set contact_channels_section to true to enable the section,
# if false, then no contact channels will be display.
#
# If a prefix property is set, it will be prepended to the value in the output HTML.
##
contact_channels_section: true
contact_channels:
  - name: email
    value: "kirk@kirkg.us"
    logo: email.svg
    prefix: "mailto:"
  - name: linkedin
    value: "https://www.linkedin.com/in/kirkgleaosn/"
    logo: linkedin.svg
  - name: github
    value: "https://github.com/kgleason"
    logo: github-mark.svg
  - name: gitlab
    value: "https://gitlab.com/kgleason"
    logo: gitlab.svg
  # - name: telegram
  #   value: "https://t.me/"
  #   logo: telegram.svg
  # - name: stackoverflow
  #   value: "https://stackoverflow.com"
  #   logo: stackoverflow.svg
  # - name: discord
  #   value: "https://discord.com/"
  #   logo: discord.svg
  # - name: mastodon
  #   value: "https://lile.cl/"
  #   logo: mastodon.svg
  # - name: threads
  #   value: "https://www.threads.net/@example"
  #   logo: threads.svg


##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"

##
# Misc configuration
##
# By default, there is a nav widget that pops up on the left side of the home page.
# This flag will disable that widget when set to false.
dot_nav: false

# By default, there is a pages area in the footer.
# This flag will disable that area when set to false.
footer_pages: false